/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  english: [
    'en/home',
    {
      type: 'category',
      label: 'Get Started',
      link: {
        type: 'doc',
        id: 'en/quick-start',
      },
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'en/quick-start',
        },
        {
          type: 'category',
          label: 'Tutorials and Datasets',
          link: {
            type: 'doc',
            id: 'en/getting-started/index',
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'en/tutorial'
            },
            {
              type: 'autogenerated',
              dirName: 'en/getting-started/example-datasets',
            },
            {
              type: 'doc',
              id: 'en/getting-started/playground',
            },
          ]
        },
        {
          type: 'doc',
          id: 'en/integrations/index',
        },
        {
          type: 'doc',
          id: 'en/supported-regions',
        },
        {
          type: 'doc',
          id: 'en/install',
        },
      ]
    },
  ]
}

module.exports = sidebars;
